name: ruler_picker
description: A new Flutter package project.
version: 0.0.1
author: BoredNerdy <theborednerdy@gmail.com>
homepage: https://github.com/BoredNerdy/ruler_picker

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  scrollable_positioned_list:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
